/* ============================================================
   MARCOS CURRICULARES — REGIÓN ANDINA
   Perú (CNEB) · Ecuador (Currículo Nacional) ·
   Colombia (EBC/DBA) · Venezuela (Currículo Bolivariano)
   ============================================================ */
import { stage, uni, tecnica, DOC_WORDS_ES } from "./fw-core.js";

export const ANDINA = [
  /* ── PERÚ ──────────────────────────────────────────────── */
  {
    code: "PE", name: "Perú", flag: "🇵🇪", lang: "es", region: "sur",
    fw: {
      short: "CNEB",
      name: "Currículo Nacional de la Educación Básica",
      authority: "MINEDU · Ministerio de Educación",
      year: "RM 281-2016 · modificatorias 2017 · Programas Curriculares por nivel",
      url: "https://www.minedu.gob.pe/curriculo/",
      codeMask: "Competencia 16 · Capacidad 2 · Estándar nivel 5 · Desempeño 3.º grado",
      codeHelp: "31 competencias transversales y de área; cada una tiene capacidades, un estándar por nivel de progresión (1–8) y desempeños por grado",
      words: DOC_WORDS_ES,
      standardWord: "Desempeño",
      unitWord: "Experiencia de aprendizaje / Unidad didáctica",
      designUnit: "Experiencia de aprendizaje con situación significativa",
      designExplain: "El CNEB planifica desde una situación significativa: un reto real y contextualizado que exige combinar capacidades. Sin situación significativa no hay competencia, solo contenido.",
      competencies: [
        "Se desenvuelve de manera autónoma a través de su motricidad",
        "Asume una vida saludable",
        "Interactúa a través de sus habilidades sociomotrices",
        "Aprecia de manera crítica manifestaciones artístico-culturales",
        "Crea proyectos desde los lenguajes artísticos",
        "Se comunica oralmente en su lengua materna",
        "Lee diversos tipos de textos escritos",
        "Escribe diversos tipos de textos",
        "Se comunica oralmente en inglés como lengua extranjera",
        "Construye su identidad",
        "Convive y participa democráticamente",
        "Construye interpretaciones históricas",
        "Gestiona responsablemente el espacio y el ambiente",
        "Gestiona responsablemente los recursos económicos",
        "Indaga mediante métodos científicos",
        "Explica el mundo físico basándose en conocimientos científicos",
        "Diseña y construye soluciones tecnológicas",
        "Resuelve problemas de cantidad",
        "Resuelve problemas de regularidad, equivalencia y cambio",
        "Resuelve problemas de forma, movimiento y localización",
        "Resuelve problemas de gestión de datos e incertidumbre",
        "Gestiona proyectos de emprendimiento económico o social",
        "Se desenvuelve en entornos virtuales generados por las TIC (transversal)",
        "Gestiona su aprendizaje de manera autónoma (transversal)",
      ],
      competenciesWord: "Competencias del CNEB",
      transversal: [
        "Enfoque de derechos", "Enfoque inclusivo o de atención a la diversidad",
        "Enfoque intercultural", "Enfoque de igualdad de género", "Enfoque ambiental",
        "Enfoque orientado al bien común", "Enfoque de búsqueda de la excelencia",
      ],
      transversalWord: "Enfoques transversales",
      assessment: "Evaluación formativa por competencias con escala literal AD (Logro destacado), A (Logro esperado), B (En proceso), C (En inicio). Se evalúa con criterios derivados de las capacidades y evidencias de aprendizaje.",
      inclusion: "SAANEE y Plan Educativo Personalizado; enfoque inclusivo obligatorio en toda planificación.",
      planParts: ["Datos generales", "Situación significativa", "Propósitos de aprendizaje (competencias, capacidades, desempeños)", "Enfoques transversales", "Criterios de evaluación y evidencias", "Secuencia didáctica: inicio, desarrollo, cierre", "Recursos y materiales", "Reflexión sobre el aprendizaje"],
      notes: "El producto de la experiencia de aprendizaje debe ser la evidencia principal de evaluación.",
    },
    stages: [
      stage("inicial", "Educación Inicial", "0–5 años",
        ["Ciclo I · 0–2 años", "Ciclo II · 3 años", "Ciclo II · 4 años", "Ciclo II · 5 años"],
        ["Personal Social", "Psicomotriz", "Comunicación", "Descubrimiento del Mundo", "Matemática", "Ciencia y Tecnología", "Castellano como segunda lengua"],
        "Área curricular", "Ciclo II obligatorio (3 a 5 años)."),
      stage("primaria", "Educación Primaria", "6–11 años",
        ["1.er grado (Ciclo III)", "2.º grado (Ciclo III)", "3.er grado (Ciclo IV)", "4.º grado (Ciclo IV)", "5.º grado (Ciclo V)", "6.º grado (Ciclo V)"],
        ["Personal Social", "Educación Física", "Comunicación", "Arte y Cultura", "Castellano como segunda lengua", "Inglés", "Matemática", "Ciencia y Tecnología", "Educación Religiosa", "Tutoría y Orientación Educativa"],
        "Área curricular", ""),
      stage("secundaria", "Educación Secundaria", "12–16 años",
        ["1.er grado (Ciclo VI)", "2.º grado (Ciclo VI)", "3.er grado (Ciclo VII)", "4.º grado (Ciclo VII)", "5.º grado (Ciclo VII)"],
        ["Desarrollo Personal, Ciudadanía y Cívica", "Ciencias Sociales", "Educación Física", "Comunicación", "Arte y Cultura", "Castellano como segunda lengua", "Inglés", "Matemática", "Ciencia y Tecnología", "Educación para el Trabajo", "Educación Religiosa", "Tutoría y Orientación Educativa"],
        "Área curricular", "Modalidades: EBR, Educación Básica Alternativa (EBA) y Educación Básica Especial (EBE)."),
      tecnica("Educación Superior Tecnológica y Técnico-Productiva", "15+ años",
        ["CETPRO · Ciclo Básico", "CETPRO · Ciclo Medio", "Instituto de Educación Superior Tecnológica (IEST)", "Escuela de Educación Superior Tecnológica (EEST)"],
        "Catálogo Nacional de la Oferta Formativa; certificación por módulos de competencia."),
      uni({ name: "Educación Superior Universitaria", ages: "16+", note: "Planificación por sílabo con competencias del perfil de egreso y créditos SUNEDU (1 crédito = 16 h teóricas o 32 prácticas)." }),
    ],
  },

  /* ── ECUADOR ───────────────────────────────────────────── */
  {
    code: "EC", name: "Ecuador", flag: "🇪🇨", lang: "es", region: "sur",
    fw: {
      short: "Currículo Nacional",
      name: "Currículo Nacional de Educación Obligatoria (destrezas con criterios de desempeño)",
      authority: "Ministerio de Educación del Ecuador",
      year: "2016 (Acuerdo MINEDUC-2016-00020-A) · Currículo Priorizado con énfasis en competencias 2021–2023",
      url: "https://educacion.gob.ec/curriculo/",
      codeMask: "CN.3.1.1",
      codeHelp: "CN = área (Ciencias Naturales) · 3 = subnivel · 1 = bloque curricular · 1 = número de destreza",
      words: DOC_WORDS_ES,
      standardWord: "Destreza con Criterios de Desempeño (DCD)",
      unitWord: "Unidad didáctica",
      designUnit: "Planificación Microcurricular (PUD)",
      designExplain: "Ecuador planifica en tres niveles de concreción: macro (currículo nacional), meso (PCI institucional) y micro (Planificación de Unidad Didáctica). El PUD parte de la destreza codificada y llega al indicador de evaluación.",
      competencies: [
        "Justicia — valorar la igualdad y la equidad",
        "Innovación — pensamiento crítico, creativo y resolución de problemas",
        "Solidaridad — convivencia, cooperación y cuidado del entorno",
      ],
      competenciesWord: "Valores del perfil de salida del bachiller ecuatoriano",
      transversal: ["Interculturalidad", "Formación de una ciudadanía democrática", "Protección del medioambiente", "Cuidado de la salud y hábitos de recreación", "Educación sexual integral", "Educación financiera"],
      transversalWord: "Ejes transversales del Buen Vivir",
      assessment: "Evaluación por indicadores de evaluación derivados de los criterios de evaluación. Escala cualitativa/cuantitativa de 0 a 10: Domina (9–10), Alcanza (7–8,99), Está próximo (4,01–6,99), No alcanza (≤4).",
      inclusion: "Adaptaciones curriculares de grado 1, 2 y 3 (de acceso, no significativas y significativas) con DIAC.",
      planParts: ["Datos informativos", "Objetivos de la unidad", "Destrezas con criterios de desempeño (códigos)", "Criterios de evaluación", "Indicadores de evaluación", "Actividades de aprendizaje", "Recursos", "Ejes transversales", "Adaptaciones curriculares"],
      notes: "El código de la destreza debe transcribirse literalmente: es el vínculo auditable con el currículo nacional.",
    },
    stages: [
      stage("inicial", "Educación Inicial", "0–5 años",
        ["Inicial 1 (0–3 años)", "Inicial 2 · Subnivel 1 (3–4 años)", "Inicial 2 · Subnivel 2 (4–5 años)"],
        ["Desarrollo Personal y Social · Identidad y Autonomía", "Desarrollo Personal y Social · Convivencia", "Descubrimiento del Medio Natural y Cultural", "Expresión y Comunicación · Comprensión y Expresión del Lenguaje", "Expresión y Comunicación · Expresión Artística", "Expresión y Comunicación · Expresión Corporal y Motricidad", "Relaciones Lógico-Matemáticas"],
        "Ámbito de desarrollo y aprendizaje", ""),
      stage("preparatoria", "Preparatoria (1.º EGB)", "5–6 años",
        ["1.º de Educación General Básica"],
        ["Identidad y Autonomía", "Convivencia", "Descubrimiento y Comprensión del Medio Natural y Cultural", "Relaciones Lógico-Matemáticas", "Comprensión y Expresión Oral y Escrita", "Comprensión y Expresión Artística", "Expresión Corporal"],
        "Ámbito de aprendizaje", "Currículo integrador por ámbitos."),
      stage("egb", "Educación General Básica (EGB)", "6–14 años",
        ["2.º EGB (Elemental)", "3.º EGB (Elemental)", "4.º EGB (Elemental)", "5.º EGB (Media)", "6.º EGB (Media)", "7.º EGB (Media)", "8.º EGB (Superior)", "9.º EGB (Superior)", "10.º EGB (Superior)"],
        ["Lengua y Literatura", "Matemática", "Ciencias Naturales", "Estudios Sociales", "Educación Cultural y Artística", "Educación Física", "Lengua Extranjera · Inglés", "Emprendimiento y Gestión", "Educación para la Ciudadanía"],
        "Área del conocimiento", "Subniveles: Elemental (2.º–4.º), Media (5.º–7.º), Superior (8.º–10.º)."),
      stage("bgu", "Bachillerato General Unificado (BGU)", "15–17 años",
        ["1.º de Bachillerato", "2.º de Bachillerato", "3.º de Bachillerato"],
        ["Lengua y Literatura", "Matemática", "Física", "Química", "Biología", "Historia", "Educación para la Ciudadanía", "Filosofía", "Emprendimiento y Gestión", "Educación Cultural y Artística", "Educación Física", "Inglés", "Módulo Interdisciplinar"],
        "Asignatura", "BGU en Ciencias o Bachillerato Técnico. Proyecto de grado obligatorio."),
      tecnica("Bachillerato Técnico y Formación Técnica", "15+ años",
        ["Bachillerato Técnico (1.º–3.º)", "Bachillerato Técnico Productivo", "Instituto Superior Técnico", "Instituto Superior Tecnológico"],
        "Figuras profesionales por familia; Formación en Centros de Trabajo (FCT)."),
      uni({ name: "Educación Superior", ages: "17+", note: "Planificación por sílabo alineado al Reglamento de Régimen Académico (CES); horas de aprendizaje con docencia, práctico-experimentales y autónomas." }),
    ],
  },

  /* ── COLOMBIA ──────────────────────────────────────────── */
  {
    code: "CO", name: "Colombia", flag: "🇨🇴", lang: "es", region: "sur",
    fw: {
      short: "EBC + DBA",
      name: "Estándares Básicos de Competencias, Derechos Básicos de Aprendizaje y Mallas de Aprendizaje",
      authority: "MEN · Ministerio de Educación Nacional",
      year: "Ley 115/1994 · Lineamientos 1998 · EBC 2006 · DBA v2 (2016) · Mallas de Aprendizaje",
      url: "https://www.mineducacion.gov.co",
      codeMask: "DBA 3 · Matemáticas · Grado 5.º",
      codeHelp: "Los DBA se numeran por área y grado; los EBC se agrupan por conjuntos de grados (1.º–3.º, 4.º–5.º, 6.º–7.º, 8.º–9.º, 10.º–11.º)",
      words: DOC_WORDS_ES,
      standardWord: "Derecho Básico de Aprendizaje (DBA)",
      unitWord: "Unidad didáctica / Secuencia",
      designUnit: "Planeación por competencias y DBA",
      designExplain: "Colombia da autonomía curricular a cada institución (PEI): el Estado fija estándares y DBA, y el colegio construye su malla curricular. La planeación debe articular EBC, DBA y la Matriz de Referencia del ICFES.",
      competencies: [
        "Competencias comunicativas", "Competencias matemáticas", "Competencias científicas",
        "Competencias ciudadanas", "Competencias socioemocionales", "Competencias laborales generales",
      ],
      competenciesWord: "Competencias básicas y transversales",
      transversal: [
        "Educación ambiental (PRAE)", "Educación para la sexualidad y construcción de ciudadanía",
        "Educación para el ejercicio de los derechos humanos", "Cátedra de la Paz (Ley 1732/2014)",
        "Educación económica y financiera", "Estilos de vida saludable", "Cátedra de Estudios Afrocolombianos",
      ],
      transversalWord: "Proyectos pedagógicos transversales obligatorios",
      assessment: "Decreto 1290/2009: cada institución define su Sistema Institucional de Evaluación (SIEE) con escala propia homologable a la nacional (Desempeño superior, alto, básico, bajo). Referencia externa: Pruebas Saber 3.º, 5.º, 9.º y 11.º.",
      inclusion: "Decreto 1421/2017: educación inclusiva con PIAR (Plan Individual de Ajustes Razonables) y DUA.",
      planParts: ["Área y grado", "Estándares Básicos de Competencias", "Derechos Básicos de Aprendizaje", "Competencias y desempeños", "Situación problematizadora", "Momentos de la clase", "Proyecto transversal articulado", "Recursos", "Evaluación según SIEE", "Ajustes razonables (PIAR)"],
      notes: "Áreas obligatorias fijadas por el Artículo 23 de la Ley 115; el 20 % del plan de estudios es de libre configuración institucional.",
    },
    stages: [
      stage("inicial", "Educación Inicial y Preescolar", "0–6 años",
        ["Primera infancia (0–2 años)", "Prejardín (3 años)", "Jardín (4 años)", "Transición (5 años)"],
        ["Juego", "Arte", "Literatura", "Exploración del medio"],
        "Actividad rectora", "Bases Curriculares para la Educación Inicial y Preescolar (2017). Transición es el grado obligatorio."),
      stage("primaria", "Educación Básica Primaria", "6–10 años",
        ["1.º", "2.º", "3.º", "4.º", "5.º"],
        ["Humanidades · Lengua Castellana", "Humanidades · Idioma Extranjero (Inglés)", "Matemáticas", "Ciencias Naturales y Educación Ambiental", "Ciencias Sociales, Historia, Geografía, Constitución Política y Democracia", "Educación Artística y Cultural", "Educación Ética y en Valores Humanos", "Educación Física, Recreación y Deportes", "Educación Religiosa", "Tecnología e Informática"],
        "Área obligatoria y fundamental", ""),
      stage("secundaria", "Educación Básica Secundaria", "11–14 años",
        ["6.º", "7.º", "8.º", "9.º"],
        ["Humanidades · Lengua Castellana", "Humanidades · Idioma Extranjero (Inglés)", "Matemáticas", "Ciencias Naturales y Educación Ambiental", "Ciencias Sociales, Historia, Geografía, Constitución Política y Democracia", "Educación Artística y Cultural", "Educación Ética y en Valores Humanos", "Educación Física, Recreación y Deportes", "Educación Religiosa", "Tecnología e Informática"],
        "Área obligatoria y fundamental", ""),
      stage("media", "Educación Media", "15–16 años",
        ["10.º", "11.º"],
        ["Lengua Castellana", "Inglés", "Matemáticas", "Cálculo", "Estadística", "Física", "Química", "Biología", "Ciencias Políticas y Económicas", "Filosofía", "Historia y Geografía", "Educación Artística", "Educación Física", "Tecnología e Informática", "Educación Religiosa", "Emprendimiento"],
        "Asignatura", "Media Académica o Media Técnica. Filosofía y Ciencias Políticas y Económicas son obligatorias en este nivel."),
      tecnica("Educación para el Trabajo y el Desarrollo Humano / SENA", "15+ años",
        ["Programa Técnico Laboral", "Articulación con la Media Técnica", "Tecnólogo SENA", "Formación Complementaria"],
        "Certificación por competencias laborales; articulación SENA–media técnica."),
      uni({ name: "Educación Superior", ages: "16+", grades: ["Técnico Profesional", "Tecnológico", "Pregrado · 1.er semestre", "Pregrado · años intermedios", "Pregrado · último año", "Especialización", "Maestría", "Doctorado"], note: "Planificación por syllabus con resultados de aprendizaje y créditos académicos (1 crédito = 48 horas)." }),
    ],
  },

  /* ── VENEZUELA ─────────────────────────────────────────── */
  {
    code: "VE", name: "Venezuela", flag: "🇻🇪", lang: "es", region: "sur",
    fw: {
      short: "Currículo Bolivariano",
      name: "Currículo Nacional Bolivariano + Proceso de Transformación Curricular",
      authority: "Ministerio del Poder Popular para la Educación (MPPE)",
      year: "CNB 2007 · Transformación Curricular de Educación Media (2016) · actualizaciones vigentes",
      url: "https://me.gob.ve",
      codeMask: "Área de Formación · Tema Generador · Referente Teórico-Práctico",
      codeHelp: "La Media se organiza por áreas de formación, temas indispensables, temas generadores y referentes teórico-prácticos",
      words: DOC_WORDS_ES,
      standardWord: "Referente teórico-práctico",
      unitWord: "Proyecto de Aprendizaje (PA)",
      designUnit: "Proyecto de Aprendizaje articulado al PEIC",
      designExplain: "Venezuela planifica por proyectos: el Proyecto de Aprendizaje del aula se articula con el Proyecto Educativo Integral Comunitario del plantel, partiendo de un diagnóstico participativo de la comunidad.",
      competencies: ["Aprender a crear", "Aprender a convivir y participar", "Aprender a valorar", "Aprender a reflexionar"],
      competenciesWord: "Pilares de la educación bolivariana",
      transversal: [
        "Ambiente y salud integral", "Interculturalidad", "Lenguaje", "Derechos Humanos y cultura de paz",
        "Trabajo liberador", "Soberanía y defensa integral de la nación", "Ciencia, tecnología e innovación",
        "Sexualidad responsable y placentera", "Preservación de la vida en el planeta",
      ],
      transversalWord: "Temas indispensables",
      assessment: "Evaluación cualitativa, formativa y participativa (autoevaluación, coevaluación y heteroevaluación); literales A–E en Primaria y escala 1–20 en Media.",
      inclusion: "Modalidad de Educación Especial con integración e Informe Psicopedagógico.",
      planParts: ["Diagnóstico integral", "Tema generador", "Referentes teórico-prácticos", "Propósito del proyecto", "Temas indispensables", "Actividades y estrategias", "Recursos", "Evaluación cualitativa", "Articulación con el PEIC"],
      notes: "El diagnóstico comunitario es el punto de partida obligatorio de la planificación.",
    },
    stages: [
      stage("inicial", "Educación Inicial", "0–6 años",
        ["Maternal (0–3 años)", "Preescolar · 1.er grupo (3–4 años)", "Preescolar · 2.º grupo (4–5 años)", "Preescolar · 3.er grupo (5–6 años)"],
        ["Formación Personal, Social y Comunicación", "Relación entre los Componentes del Ambiente"],
        "Área de aprendizaje", ""),
      stage("primaria", "Educación Primaria", "6–11 años",
        ["1.er grado", "2.º grado", "3.er grado", "4.º grado", "5.º grado", "6.º grado"],
        ["Lenguaje, Comunicación y Cultura", "Matemática, Ciencias Naturales y Sociedad", "Ciencias Sociales, Ciudadanía e Identidad", "Educación Física, Deportes y Recreación"],
        "Área de aprendizaje", ""),
      stage("media", "Educación Media General", "12–16 años",
        ["1.er año", "2.º año", "3.er año", "4.º año", "5.º año"],
        ["Castellano", "Matemática", "Ciencias Naturales", "Biología", "Física", "Química", "Geografía, Historia y Ciudadanía", "Inglés y otras Lenguas Extranjeras", "Educación Física", "Arte y Patrimonio", "Orientación y Convivencia", "Participación en Grupos de Creación, Recreación y Producción", "Formación para la Soberanía Nacional"],
        "Área de formación", "Media Técnica se extiende a 6.º año con título de Técnico Medio."),
      tecnica("Educación Media Técnica", "12+ años", ["1.º a 6.º año de Media Técnica", "Escuela Técnica Robinsoniana", "Programa Nacional de Formación (PNF)"], ""),
      uni({ name: "Educación Universitaria", ages: "17+", note: "Programas Nacionales de Formación (PNF) organizados por trayectos y unidades curriculares." }),
    ],
  },
];
