/* ============================================================
   MARCOS CURRICULARES — PENÍNSULA IBÉRICA
   España (LOMLOE) · Portugal (Perfil dos Alunos + AE)
   ============================================================ */
import { stage, uni, tecnica, DOC_WORDS_ES, DOC_WORDS_PT } from "./fw-core.js";

export const IBERIA = [
  /* ── ESPAÑA ────────────────────────────────────────────── */
  {
    code: "ES", name: "España", flag: "🇪🇸", lang: "es", region: "europa",
    fw: {
      short: "LOMLOE",
      name: "Ley Orgánica 3/2020 (LOMLOE) — currículo por competencias",
      authority: "Ministerio de Educación, FP y Deportes + Consejerías autonómicas",
      year: "2020 · desarrollo curricular 2022 (RD 95/2022, 157/2022, 217/2022, 243/2022)",
      url: "https://www.educacionfpydeportes.gob.es/portada.html",
      codeMask: "CE 3.2 · CCL2 · 2.º ciclo",
      codeHelp: "CE = competencia específica · el segundo número es el criterio de evaluación asociado",
      words: DOC_WORDS_ES,
      standardWord: "Criterio de evaluación",
      unitWord: "Situación de aprendizaje",
      /* La pieza central del diseño LOMLOE */
      designUnit: "Situación de aprendizaje",
      designExplain: "La LOMLOE no planifica por temas sino por situaciones de aprendizaje: un reto contextualizado que moviliza competencias específicas y se evalúa con criterios de evaluación, no con exámenes de contenido.",
      competencies: [
        "CCL · Competencia en comunicación lingüística",
        "CP · Competencia plurilingüe",
        "STEM · Competencia matemática y en ciencia, tecnología e ingeniería",
        "CD · Competencia digital",
        "CPSAA · Competencia personal, social y de aprender a aprender",
        "CC · Competencia ciudadana",
        "CE · Competencia emprendedora",
        "CCEC · Competencia en conciencia y expresión culturales",
      ],
      competenciesWord: "Competencias clave del Perfil de salida",
      transversal: [
        "Educación para la salud (incluida la afectivo-sexual)",
        "Educación para el consumo responsable y el desarrollo sostenible",
        "Educación para la paz y los derechos humanos",
        "Igualdad efectiva entre mujeres y hombres",
        "Educación digital y uso crítico de la tecnología",
        "Educación emocional y en valores",
      ],
      transversalWord: "Elementos transversales",
      assessment: "Evaluación criterial, continua, formativa e integradora. Se califica por criterios de evaluación asociados a competencias específicas, mediante rúbricas y evidencias variadas. La promoción es una decisión colegiada del equipo docente.",
      inclusion: "DUA obligatorio (Diseño Universal para el Aprendizaje) + medidas de atención a la diversidad ordinarias y extraordinarias; Plan de Atención a la Diversidad de centro.",
      planParts: ["Justificación y contextualización", "Competencias específicas", "Criterios de evaluación", "Saberes básicos", "Descriptores operativos del Perfil de salida", "Secuencia de actividades", "Medidas DUA", "Instrumentos de evaluación", "Elementos transversales"],
      notes: "Cada Comunidad Autónoma concreta el 40–50 % del currículo; el módulo genera el tronco estatal y permite anotar la concreción autonómica.",
    },
    stages: [
      stage("infantil", "Educación Infantil", "0–6 años",
        ["1er ciclo · 0–1 año", "1er ciclo · 1–2 años", "1er ciclo · 2–3 años", "2º ciclo · 3 años", "2º ciclo · 4 años", "2º ciclo · 5 años"],
        ["Crecimiento en armonía", "Descubrimiento y exploración del entorno", "Comunicación y representación de la realidad"],
        "Área", "Currículo por áreas globalizadas; el juego y la experimentación son el método, no un recurso. RD 95/2022."),
      stage("primaria", "Educación Primaria", "6–12 años",
        ["1.º de Primaria", "2.º de Primaria", "3.º de Primaria", "4.º de Primaria", "5.º de Primaria", "6.º de Primaria"],
        ["Conocimiento del Medio Natural, Social y Cultural", "Educación Artística", "Educación Física", "Lengua Castellana y Literatura", "Lengua Cooficial y Literatura", "Lengua Extranjera", "Matemáticas", "Educación en Valores Cívicos y Éticos", "Religión / Atención educativa"],
        "Área", "Organizada en tres ciclos de dos cursos. RD 157/2022."),
      stage("eso", "Educación Secundaria Obligatoria (ESO)", "12–16 años",
        ["1.º de ESO", "2.º de ESO", "3.º de ESO", "4.º de ESO"],
        ["Biología y Geología", "Física y Química", "Geografía e Historia", "Lengua Castellana y Literatura", "Lengua Extranjera", "Matemáticas", "Educación Física", "Educación Plástica, Visual y Audiovisual", "Música", "Tecnología y Digitalización", "Educación en Valores Cívicos y Éticos", "Latín", "Economía y Emprendimiento", "Digitalización", "Formación y Orientación Personal y Profesional"],
        "Materia", "4.º de ESO se organiza en opciones orientadas a Bachillerato o a FP. RD 217/2022."),
      stage("bachillerato", "Bachillerato", "16–18 años",
        ["1.º de Bachillerato", "2.º de Bachillerato"],
        ["Lengua Castellana y Literatura", "Filosofía", "Historia de España", "Historia de la Filosofía", "Lengua Extranjera", "Matemáticas I y II", "Matemáticas Aplicadas a las Ciencias Sociales", "Física", "Química", "Biología", "Geología y Ciencias Ambientales", "Dibujo Técnico", "Tecnología e Ingeniería", "Latín", "Griego", "Historia del Arte", "Historia del Mundo Contemporáneo", "Economía", "Empresa y Diseño de Modelos de Negocio", "Geografía", "Literatura Universal", "Artes Escénicas", "Análisis Musical", "Cultura Audiovisual", "Diseño"],
        "Materia", "Modalidades: Ciencias y Tecnología · Humanidades y Ciencias Sociales · Artes · General. RD 243/2022."),
      tecnica("Formación Profesional", "16+ años",
        ["FP Grado Básico", "FP Grado Medio", "FP Grado Superior", "Cursos de Especialización", "Microformaciones (Grado A/B/C)"],
        "Ley Orgánica 3/2022 de FP: sistema único con formación dual obligatoria en todos los grados."),
      uni({ name: "Universidad (EEES)", ages: "18+", grades: ["Grado · 1.º", "Grado · 2.º", "Grado · 3.º", "Grado · 4.º", "Máster Universitario", "Doctorado"], note: "Planificación por guía docente: competencias, resultados de aprendizaje y ECTS (1 ECTS = 25–30 h de trabajo del estudiante)." }),
    ],
  },

  /* ── PORTUGAL ──────────────────────────────────────────── */
  {
    code: "PT", name: "Portugal", flag: "🇵🇹", lang: "pt", region: "europa",
    fw: {
      short: "PASEO + AE",
      name: "Perfil dos Alunos à Saída da Escolaridade Obrigatória + Aprendizagens Essenciais",
      authority: "Ministério da Educação · Direção-Geral da Educação (DGE)",
      year: "2017 (Perfil) · 2018 DL 55/2018 e DL 54/2018 · AE revistas 2021–2024",
      url: "https://www.dge.mec.pt/aprendizagens-essenciais-0",
      codeMask: "AE · 7.º ano · Domínio: Números e Operações",
      codeHelp: "As Aprendizagens Essenciais organizam-se por ano, disciplina e domínio/tema",
      words: DOC_WORDS_PT,
      standardWord: "Aprendizagem Essencial",
      unitWord: "Domínio de Autonomia Curricular (DAC)",
      designUnit: "Planificação por Aprendizagens Essenciais e DAC",
      designExplain: "O currículo português articula três documentos: o Perfil dos Alunos define o para quê, as Aprendizagens Essenciais definem o quê, e a Estratégia Nacional de Educação para a Cidadania atravessa tudo. Os DAC permitem trabalho interdisciplinar por projeto.",
      competencies: [
        "A · Linguagens e textos",
        "B · Informação e comunicação",
        "C · Raciocínio e resolução de problemas",
        "D · Pensamento crítico e pensamento criativo",
        "E · Relacionamento interpessoal",
        "F · Desenvolvimento pessoal e autonomia",
        "G · Bem-estar, saúde e ambiente",
        "H · Sensibilidade estética e artística",
        "I · Saber científico, técnico e tecnológico",
        "J · Consciência e domínio do corpo",
      ],
      competenciesWord: "Áreas de Competências do Perfil dos Alunos",
      transversal: [
        "Direitos Humanos", "Igualdade de Género", "Interculturalidade",
        "Desenvolvimento Sustentável", "Educação Ambiental", "Saúde",
        "Sexualidade", "Media", "Instituições e participação democrática",
        "Literacia financeira e educação para o consumo", "Segurança rodoviária", "Risco",
      ],
      transversalWord: "Domínios da Estratégia Nacional de Educação para a Cidadania (ENEC)",
      assessment: "Avaliação formativa como principal modalidade, com diversificação de instrumentos e feedback descritivo de qualidade. A avaliação sumativa traduz-se em menções qualitativas no 1.º ciclo e classificações de 1 a 5 (básico) ou 0 a 20 (secundário).",
      inclusion: "DL 54/2018 — abordagem multinível: medidas universais, seletivas e adicionais. Não existem categorias de alunos; existem medidas de suporte à aprendizagem.",
      planParts: ["Aprendizagens Essenciais mobilizadas", "Áreas de Competências do Perfil", "Domínios de Cidadania", "Estratégias de ensino", "Recursos e materiais", "Instrumentos de avaliação formativa", "Medidas de suporte à aprendizagem", "Articulação interdisciplinar (DAC)"],
      notes: "A Flexibilidade Curricular (DL 55/2018) permite gerir até 25 % da carga horária de forma autónoma pela escola.",
    },
    stages: [
      stage("preescolar", "Educação Pré-Escolar", "3–6 anos",
        ["3 anos", "4 anos", "5 anos"],
        ["Formação Pessoal e Social", "Expressão e Comunicação · Motora", "Expressão e Comunicação · Dramática", "Expressão e Comunicação · Plástica", "Expressão e Comunicação · Musical", "Expressão e Comunicação · Dança", "Domínio da Linguagem Oral e Abordagem à Escrita", "Domínio da Matemática", "Conhecimento do Mundo"],
        "Área de conteúdo", "Regem as OCEPE — Orientações Curriculares para a Educação Pré-Escolar (2016)."),
      stage("basico1", "Ensino Básico · 1.º Ciclo", "6–10 anos",
        ["1.º ano", "2.º ano", "3.º ano", "4.º ano"],
        ["Português", "Matemática", "Estudo do Meio", "Educação Artística · Artes Visuais", "Educação Artística · Expressão Dramática/Teatro", "Educação Artística · Dança", "Educação Artística · Música", "Educação Física", "Inglês (3.º e 4.º)", "Cidadania e Desenvolvimento", "Apoio ao Estudo", "TIC"],
        "Disciplina", "Regime de monodocência coadjuvada."),
      stage("basico2", "Ensino Básico · 2.º Ciclo", "10–12 anos",
        ["5.º ano", "6.º ano"],
        ["Português", "Inglês", "História e Geografia de Portugal", "Matemática", "Ciências Naturais", "Educação Visual", "Educação Tecnológica", "Educação Musical", "Educação Física", "Cidadania e Desenvolvimento", "TIC", "Educação Moral e Religiosa"],
        "Disciplina", ""),
      stage("basico3", "Ensino Básico · 3.º Ciclo", "12–15 anos",
        ["7.º ano", "8.º ano", "9.º ano"],
        ["Português", "Inglês", "Língua Estrangeira II (Francês/Espanhol/Alemão)", "História", "Geografia", "Matemática", "Ciências Naturais", "Físico-Química", "Educação Visual", "Educação Física", "TIC", "Complemento à Educação Artística", "Cidadania e Desenvolvimento", "Educação Moral e Religiosa"],
        "Disciplina", "Fim da escolaridade básica; provas de aferição e prova final no 9.º ano."),
      stage("secundario", "Ensino Secundário", "15–18 anos",
        ["10.º ano", "11.º ano", "12.º ano"],
        ["Português", "Filosofia", "Educação Física", "Inglês", "Matemática A", "Matemática B", "Matemática Aplicada às Ciências Sociais (MACS)", "Física e Química A", "Biologia e Geologia", "Geometria Descritiva A", "História A", "História B", "História da Cultura e das Artes", "Geografia A", "Economia A", "Literatura Portuguesa", "Latim A", "Desenho A", "Psicologia B", "Sociologia", "Direito", "Biologia", "Física", "Química", "Geologia"],
        "Disciplina", "Cursos Científico-Humanísticos: Ciências e Tecnologias · Ciências Socioeconómicas · Línguas e Humanidades · Artes Visuais."),
      tecnica("Ensino Profissional e Cursos Profissionais", "15+ anos",
        ["Cursos Profissionais (nível 4)", "Cursos de Aprendizagem", "Cursos de Especialização Tecnológica (nível 5)", "Ensino Artístico Especializado"],
        "Estrutura modular com Formação Sociocultural, Científica e Técnica + Formação em Contexto de Trabalho (FCT) e Prova de Aptidão Profissional (PAP)."),
      uni({ name: "Ensino Superior (EEES)", ages: "18+", grades: ["Licenciatura · 1.º ano", "Licenciatura · 2.º ano", "Licenciatura · 3.º ano", "Mestrado", "Mestrado Integrado", "Doutoramento"], subjectWord: "Área científica", note: "Planeamento por Ficha de Unidade Curricular (FUC): objetivos, conteúdos, metodologias, avaliação e ECTS." }),
    ],
  },
];
