/* ============================================================
   MARCOS CURRICULARES — AMÉRICA DEL NORTE
   México (NEM · Plan 2022) · Estados Unidos (CCSS/NGSS/C3) ·
   Canadá (currículos provinciales)
   ============================================================ */
import { stage, uni, tecnica, DOC_WORDS_ES, DOC_WORDS_EN } from "./fw-core.js";

export const NORTE = [
  /* ── MÉXICO ────────────────────────────────────────────── */
  {
    code: "MX", name: "México", flag: "🇲🇽", lang: "es", region: "norte",
    fw: {
      short: "NEM · Plan 2022",
      name: "Nueva Escuela Mexicana — Plan de Estudio 2022 para la Educación Básica",
      authority: "SEP · Secretaría de Educación Pública",
      year: "Acuerdo 14/08/22 · Programas sintéticos 2023 · MCCEMS 2023 para Media Superior",
      url: "https://educacionbasica.sep.gob.mx",
      codeMask: "Fase 4 · Campo: Saberes y Pensamiento Científico · Eje: Pensamiento crítico",
      codeHelp: "El currículo se organiza en 6 fases (no en grados), 4 campos formativos y 7 ejes articuladores",
      words: DOC_WORDS_ES,
      standardWord: "Contenido y Proceso de Desarrollo de Aprendizaje (PDA)",
      unitWord: "Proyecto (de aula, escolar o comunitario)",
      designUnit: "Plano didáctico con proyecto comunitario",
      designExplain: "La NEM abandona los aprendizajes esperados por grado: se planifica por fases, campos formativos y ejes articuladores, y el vehículo obligatorio es el proyecto. El docente codiseña el programa analítico a partir de una lectura de la realidad de su comunidad.",
      competencies: [
        "Inclusión", "Pensamiento crítico", "Interculturalidad crítica", "Igualdad de género",
        "Vida saludable", "Apropiación de las culturas a través de la lectura y la escritura",
        "Artes y experiencias estéticas",
      ],
      competenciesWord: "Ejes articuladores",
      transversal: ["Educación para la paz", "Perspectiva de género", "Educación ambiental y cambio climático", "Interculturalidad y pueblos originarios", "Salud y bienestar socioemocional", "Cultura digital crítica", "Derechos de niñas, niños y adolescentes"],
      transversalWord: "Temas de relevancia social",
      assessment: "Evaluación formativa y cualitativa centrada en procesos; se valora el avance en los PDA mediante evidencias del proyecto. Boleta con escala numérica en Primaria y Secundaria a partir de 3.º.",
      inclusion: "Educación inclusiva con DUA y Unidades de Servicios de Apoyo a la Educación Regular (USAER).",
      planParts: ["Lectura de la realidad / diagnóstico comunitario", "Fase y campos formativos", "Contenidos y PDA", "Ejes articuladores", "Metodología (ABP comunitario, ABP, aprendizaje-servicio, STEAM)", "Momentos del proyecto: planeación, acción, intervención, evaluación", "Recursos y materiales", "Evaluación formativa y evidencias", "Producto comunitario"],
      notes: "Metodologías oficiales por campo: Aprendizaje Basado en Proyectos Comunitarios, Aprendizaje Basado en Indagación (STEAM), Aprendizaje Servicio y Aprendizaje Basado en Problemas.",
    },
    stages: [
      stage("inicial", "Educación Inicial · Fase 1", "0–3 años",
        ["Lactantes", "Maternales"],
        ["Lenguajes", "Saberes y Pensamiento Científico", "Ética, Naturaleza y Sociedades", "De lo Humano y lo Comunitario"],
        "Campo formativo", "Fase 1 del Plan 2022."),
      stage("preescolar", "Educación Preescolar · Fase 2", "3–6 años",
        ["1.º de Preescolar", "2.º de Preescolar", "3.º de Preescolar"],
        ["Lenguajes", "Saberes y Pensamiento Científico", "Ética, Naturaleza y Sociedades", "De lo Humano y lo Comunitario"],
        "Campo formativo", ""),
      stage("primaria", "Educación Primaria · Fases 3, 4 y 5", "6–12 años",
        ["1.º de Primaria (Fase 3)", "2.º de Primaria (Fase 3)", "3.º de Primaria (Fase 4)", "4.º de Primaria (Fase 4)", "5.º de Primaria (Fase 5)", "6.º de Primaria (Fase 5)"],
        ["Lenguajes", "Saberes y Pensamiento Científico", "Ética, Naturaleza y Sociedades", "De lo Humano y lo Comunitario"],
        "Campo formativo", "Los campos sustituyen a las asignaturas tradicionales."),
      stage("secundaria", "Educación Secundaria · Fase 6", "12–15 años",
        ["1.º de Secundaria", "2.º de Secundaria", "3.º de Secundaria"],
        ["Lenguajes · Español", "Lenguajes · Inglés", "Lenguajes · Artes", "Saberes y Pensamiento Científico · Matemáticas", "Saberes y Pensamiento Científico · Biología", "Saberes y Pensamiento Científico · Física", "Saberes y Pensamiento Científico · Química", "Ética, Naturaleza y Sociedades · Historia", "Ética, Naturaleza y Sociedades · Geografía", "Ética, Naturaleza y Sociedades · Formación Cívica y Ética", "De lo Humano y lo Comunitario · Educación Física", "De lo Humano y lo Comunitario · Tecnología", "De lo Humano y lo Comunitario · Tutoría y Educación Socioemocional"],
        "Campo formativo / Disciplina", ""),
      stage("media_superior", "Educación Media Superior (MCCEMS)", "15–18 años",
        ["1.er semestre", "2.º semestre", "3.er semestre", "4.º semestre", "5.º semestre", "6.º semestre"],
        ["Recursos Sociocognitivos · Lengua y Comunicación", "Recursos Sociocognitivos · Pensamiento Matemático", "Recursos Sociocognitivos · Conciencia Histórica", "Recursos Sociocognitivos · Cultura Digital", "Recursos Sociocognitivos · Inglés", "Áreas de Conocimiento · Ciencias Naturales, Experimentales y Tecnología", "Áreas de Conocimiento · Ciencias Sociales", "Áreas de Conocimiento · Humanidades", "Recursos Socioemocionales · Responsabilidad Social", "Recursos Socioemocionales · Cuidado Físico Corporal", "Recursos Socioemocionales · Bienestar Emocional Afectivo", "Currículum Laboral"],
        "Recurso / Área de conocimiento", "Marco Curricular Común de la Educación Media Superior (MCCEMS), vigente desde 2023."),
      tecnica("Educación Media Superior Tecnológica y Formación para el Trabajo", "15+ años",
        ["CONALEP", "CBTis / CETis (DGETI)", "CBTA (DGETAyCM)", "CECyTE", "Bachillerato Tecnológico"],
        "Formación bivalente: bachillerato + carrera técnica con certificado de competencias."),
      uni({ name: "Educación Superior", ages: "17+", grades: ["Técnico Superior Universitario", "Licenciatura · 1.er año", "Licenciatura · años intermedios", "Licenciatura · último año", "Especialidad", "Maestría", "Doctorado"], note: "Planificación por programa de asignatura con créditos SATCA (1 crédito = 16 horas)." }),
    ],
  },

  /* ── ESTADOS UNIDOS ────────────────────────────────────── */
  {
    code: "US", name: "Estados Unidos", flag: "🇺🇸", lang: "en", region: "norte",
    fw: {
      short: "CCSS · NGSS · C3",
      name: "Common Core State Standards, Next Generation Science Standards y C3 Framework",
      authority: "No hay currículo federal — estándares estatales; CCSSO/NGA para CCSS, Achieve para NGSS, NCSS para C3",
      year: "CCSS 2010 · NGSS 2013 · C3 2013 · National Core Arts Standards 2014 · ISTE Standards 2016/2024",
      url: "https://www.thecorestandards.org",
      codeMask: "CCSS.MATH.CONTENT.5.NBT.A.1 · NGSS MS-LS1-1",
      codeHelp: "CCSS: materia.grado.dominio.cluster.estándar · NGSS: nivel-disciplina-número (MS = Middle School)",
      words: DOC_WORDS_EN,
      standardWord: "Standard",
      unitWord: "Unit / Lesson",
      designUnit: "Backward Design (Understanding by Design)",
      designExplain: "El estándar estadounidense de planificación es Understanding by Design: se parte de los resultados deseados, se definen las evidencias de evaluación aceptables y solo entonces se planifican las experiencias de aprendizaje. La educación es competencia estatal, así que el módulo permite anclar al estándar del estado.",
      competencies: [
        "Critical thinking", "Communication", "Collaboration", "Creativity",
        "Information literacy", "Media literacy", "Technology literacy",
        "Flexibility", "Leadership", "Initiative", "Productivity", "Social skills",
      ],
      competenciesWord: "Framework for 21st Century Learning (4C + literacies + life skills)",
      transversal: ["Social and Emotional Learning (CASEL)", "Digital citizenship (ISTE)", "Culturally responsive teaching", "Financial literacy", "Career readiness", "Civic education", "Environmental & sustainability education"],
      transversalWord: "Cross-cutting priorities",
      assessment: "Formative assessment plus standards-based grading; state summative assessments (Smarter Balanced, PARCC-legacy, state-specific), plus AP/IB and SAT/ACT at high school.",
      inclusion: "IDEA — Individualized Education Program (IEP) y Section 504 Plans; UDL (CAST) como marco de diseño.",
      planParts: ["Standards addressed", "Learning objectives (I can…)", "Essential question", "Assessment evidence (formative & summative)", "Materials", "Lesson sequence: hook, direct instruction, guided practice, independent practice, closure", "Differentiation & UDL supports", "Accommodations (IEP/504/ELL)", "Extension & homework"],
      notes: "Estados con estándares propios destacados: Texas (TEKS), Florida (B.E.S.T.), Virginia (SOL), Nueva York (Next Generation Learning Standards), California (CA CCSS + CA NGSS).",
    },
    stages: [
      stage("early", "Early Childhood / Pre-K", "3–5 years",
        ["Pre-K 3", "Pre-K 4", "Transitional Kindergarten"],
        ["Language and Literacy", "Mathematics", "Science and Technology", "Social Studies", "Creative Arts", "Physical Development and Health", "Social and Emotional Development", "Approaches to Learning"],
        "Domain", "Head Start Early Learning Outcomes Framework y estándares estatales de early learning."),
      stage("elementary", "Elementary School", "5–11 years",
        ["Kindergarten", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5"],
        ["English Language Arts", "Mathematics", "Science", "Social Studies", "Visual Arts", "Music", "Physical Education", "Health", "World Languages", "Computer Science / Technology", "Library & Information Literacy"],
        "Subject", ""),
      stage("middle", "Middle School", "11–14 years",
        ["Grade 6", "Grade 7", "Grade 8"],
        ["English Language Arts", "Mathematics", "Pre-Algebra", "Algebra I", "Life Science", "Earth and Space Science", "Physical Science", "World History", "U.S. History", "Geography", "Civics", "Visual Arts", "Music", "Physical Education", "Health", "World Languages", "Computer Science", "Career and Technical Education"],
        "Course", ""),
      stage("high", "High School", "14–18 years",
        ["Grade 9 (Freshman)", "Grade 10 (Sophomore)", "Grade 11 (Junior)", "Grade 12 (Senior)"],
        ["English I–IV", "Algebra I", "Geometry", "Algebra II", "Pre-Calculus", "Calculus / AP Calculus", "Statistics", "Biology", "Chemistry", "Physics", "Environmental Science", "U.S. History", "World History", "U.S. Government", "Economics", "Psychology", "Visual Arts", "Music / Band / Choir", "Theatre", "Physical Education", "Health", "Spanish / French / Mandarin", "Computer Science / AP CSP", "Engineering (PLTW)", "Business", "Journalism"],
        "Course", "Créditos Carnegie para graduación; AP, IB, dual enrollment y honors."),
      tecnica("Career and Technical Education (CTE)", "14+ years",
        ["CTE Pathway (High School)", "Certificate Program", "Associate Degree (Community College)", "Apprenticeship"],
        "16 Career Clusters del Advance CTE; Perkins V financia la articulación."),
      uni({ name: "Higher Education", ages: "17+", grades: ["Freshman", "Sophomore", "Junior", "Senior", "Master's", "Doctoral / PhD"], subjectWord: "Discipline", note: "Course syllabus with learning outcomes and credit hours; accreditation by regional bodies." }),
    ],
  },

  /* ── CANADÁ ────────────────────────────────────────────── */
  {
    code: "CA", name: "Canadá", flag: "🇨🇦", lang: "en", region: "norte",
    fw: {
      short: "Provincial Curricula",
      name: "Currículos provinciales y territoriales (Ontario, BC, Alberta, Québec PFEQ…)",
      authority: "No hay ministerio federal de educación: cada provincia/territorio define su currículo (CMEC coordina)",
      year: "BC Redesigned Curriculum 2016–2019 · Ontario revisions 2020–2023 · Québec PFEQ + PDA · Alberta 2022–2024",
      url: "https://www.cmec.ca",
      codeMask: "BC: Big Idea + Curricular Competency + Content · ON: Overall & Specific Expectations",
      codeHelp: "British Columbia usa Big Ideas / Curricular Competencies / Content; Ontario usa Overall y Specific Expectations por strand",
      words: DOC_WORDS_EN,
      standardWord: "Learning Standard / Expectation",
      unitWord: "Unit of Inquiry",
      designUnit: "Concept-based planning (Big Ideas + Core Competencies)",
      designExplain: "El modelo canadiense contemporáneo — especialmente el de British Columbia — planifica desde Big Ideas duraderas, competencias curriculares (el hacer) y contenido (el saber), en lugar de listas de objetivos. Incluye por mandato la perspectiva indígena (First Peoples Principles of Learning).",
      competencies: [
        "Communication · Communicating",
        "Communication · Collaborating",
        "Thinking · Critical and Reflective Thinking",
        "Thinking · Creative Thinking",
        "Personal and Social · Personal Awareness and Responsibility",
        "Personal and Social · Positive Personal and Cultural Identity",
        "Personal and Social · Social Awareness and Responsibility",
      ],
      competenciesWord: "Core Competencies (BC model)",
      transversal: ["First Peoples Principles of Learning / Indigenous ways of knowing", "Truth and Reconciliation (Calls to Action 62–63)", "Environmental sustainability and climate education", "Digital literacy and citizenship", "Mental health and well-being", "Equity, diversity and inclusion", "Financial literacy", "Career-life education"],
      transversalWord: "Cross-curricular priorities",
      assessment: "Assessment for, as and of learning; proficiency scales (Emerging, Developing, Proficient, Extending) en BC, letter grades y achievement charts (Knowledge, Thinking, Communication, Application) en Ontario.",
      inclusion: "Individual Education Plan (IEP) e inclusive education policy provincial; UDL ampliamente adoptado.",
      planParts: ["Big Ideas", "Curricular Competencies", "Content / Expectations", "Core Competencies", "Indigenous perspectives (First Peoples Principles)", "Learning intentions & success criteria", "Assessment plan (for/as/of learning)", "Universal Design for Learning", "Resources"],
      notes: "Québec funciona con el PFEQ (Programme de formation de l'école québécoise) y las Progressions des apprentissages; el sistema incluye el Cégep entre secundaria y universidad.",
    },
    stages: [
      stage("early", "Early Learning / Kindergarten", "4–6 years",
        ["Junior Kindergarten", "Senior Kindergarten", "Maternelle (QC)"],
        ["Belonging and Contributing", "Self-Regulation and Well-Being", "Demonstrating Literacy and Mathematics Behaviours", "Problem Solving and Innovating"],
        "Frame", "Ontario Kindergarten Program organiza el aprendizaje en cuatro frames."),
      stage("elementary", "Elementary School", "6–12 years",
        ["Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6"],
        ["Language / English Language Arts", "Français", "Mathematics", "Science and Technology", "Social Studies", "Health and Physical Education", "The Arts · Visual Arts", "The Arts · Music", "The Arts · Drama", "The Arts · Dance", "Applied Design, Skills and Technologies (ADST)", "Career Education", "Indigenous Studies"],
        "Subject", ""),
      stage("middle", "Middle / Intermediate", "12–14 years",
        ["Grade 7", "Grade 8", "Secondaire 1 (QC)", "Secondaire 2 (QC)"],
        ["English Language Arts", "Français", "Mathematics", "Science", "Social Studies / History and Geography", "Health and Physical Education", "The Arts", "Applied Design, Skills and Technologies", "Career Education", "Second Languages"],
        "Subject", ""),
      stage("secondary", "Secondary / High School", "14–18 years",
        ["Grade 9", "Grade 10", "Grade 11", "Grade 12", "Secondaire 3–5 (QC)"],
        ["English", "Français langue d'enseignement", "Mathematics · Workplace", "Mathematics · Pre-Calculus", "Mathematics · Foundations", "Calculus", "Biology", "Chemistry", "Physics", "Earth Sciences", "Environmental Science", "Social Studies", "History", "Geography", "Law", "Economics", "Psychology", "Visual Arts", "Music", "Drama", "Physical and Health Education", "Applied Design, Skills and Technologies", "Computer Science", "Career-Life Education", "Career-Life Connections", "Indigenous Studies"],
        "Course", "Graduación por créditos provinciales; en Québec el Diplôme d'études secondaires precede al Cégep."),
      tecnica("Skilled Trades and Career Programs", "15+ years",
        ["Youth Apprenticeship (Grade 11–12)", "Trades Training / Foundation Program", "College Diploma", "Red Seal Apprenticeship"],
        "Programa Red Seal para estandarización interprovincial de oficios."),
      uni({ name: "Post-Secondary Education", ages: "17+", grades: ["Cégep (QC) · 1re année", "Cégep (QC) · 2e année", "Undergraduate Year 1", "Undergraduate Year 2", "Undergraduate Year 3", "Undergraduate Year 4", "Master's", "Doctoral"], subjectWord: "Faculty / Discipline" }),
    ],
  },
];
